Default: &defaults
  host: "localhost"
  port: 3000
  copyright: Free as in free beer
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://www.example.com"
  <<: *defaults
