Default: &defaults
  database: ratetouille.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Test:
  database: ratetouille_test.sqlite3
  <<: *defaults

Staging:
  database: ratetouille_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: ratetouille_production.sqlite3
  poolsize: 100
  <<: *defaults
